### ISSUE TITLE
cmake doesn't accept SCIP 9 anymore

### ISSUE THREAD

**Issue by svigerske** [scipopt/JSCIPOpt#52]
With 8fdef68, our interface tests fail with
```
CMake Error at CMakeLists.txt:78 (find_package):
  Could not find a configuration file for package "SCIP" that is compatible
  with requested version "8.0.0".

  The following configuration files were considered but not accepted:

    [<https://cijenkins.zib.de/job/SCIPOptSuite_test_interfaces/ws/scipoptsuite-9.1.2/build/scip/scip-config.cmake,>](https://cijenkins.zib.de/job/SCIPOptSuite_test_interfaces/ws/scipoptsuite-9.1.2/build/scip/scip-config.cmake,) version: 9.1.2
```
I assume the "at least" of "at least SCIP 8.0.0" didn't work.

**Comment by kkofler** [comment]
Looks like it is trying to enforce semver compatibility rules, where 9.… is "incompatible" with 8.…. It should not be doing this by default, especially considering that there is no easy option to disable this behavior. (There is only `EXACT` which does an even stricter match.) It is possible to specify a version range, but no open-ended range, and it also requires support from both the used version of CMake (the minimum currently accepted, 3.3, does not support this, only 3.19 and newer do) and the individual `Find*.cmake`/`*Config.cmake` module.

The easiest way to work around this is probably to not specify a version in `find_package` at all, but to check it manually with `if (SCIP_VERSION VERSION_LESS "8.0.0")`. I will try this later today.

**Comment by kkofler** [comment]
This is actually a misfeature of the SCIP build system.

`scip/src/CMakeLists.txt` has this:
```cmake
write_basic_package_version_file(
${PROJECT_BINARY_DIR}/scip-config-version.cmake
    VERSION ${SCIP_VERSION_MAJOR}.${SCIP_VERSION_MINOR}.${SCIP_VERSION_PATCH}
    COMPATIBILITY SameMajorVersion
    )
```
The `SameMajorVersion` there is causing this behavior. See the generated `scip-config-version.cmake` to see the behavior. (You cannot even specify a range like `8.0.0...9.9.9` or `8.0.0...<10.0.0`, it will reject any range that is not restricted to a single major version.)

I will work around this as described in my previous comment, but it should really be fixed in SCIP. The compatibility should be `AnyNewerVersion`. If a dependent package really wants to specify SCIP 8.x.x only, it should request the range `8.0.0...<9.0.0` explicity. It should not be done by default, especially because there is no way to opt out of this behavior.

**Comment by kkofler** [comment]
Filed scip#116 for this.
